

from odoo.tests import common
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

class TestAbsenceDay(common.TransactionCase):

    def setUp(self):
        super(TestAbsenceDay, self).setUp()
        
        self.HrContract = self.env['hr.contract']
        self.HrEmployee = self.env['hr.employee']
        self.HrWorkEntryType = self.env['hr.work.entry.type']
        self.ResourceCalendar = self.env['resource.calendar']
        self.HrContractUpdateWizard = self.env['hr.contract.update.wizard']

        # Create test employee
        self.employee = self.HrEmployee.create({
            'name': 'Test Employee',
        })

        self.work_entry_type_regular = self.HrWorkEntryType.search([('code', '=', 'WORK100')], limit=1)
        if not self.work_entry_type_regular:
            self.work_entry_type_regular = self.HrWorkEntryType.create({
                'name': 'Regular',
                'code': 'WORK100',
            })

        self.work_entry_type_night = self.HrWorkEntryType.search([('code', '=', 'WORKN')], limit=1)
        if not self.work_entry_type_night:
            self.work_entry_type_night = self.HrWorkEntryType.create({
                'name': 'Night shift',
                'code': 'WORKN',
            })

        # Create test calendar
        self.calendar = self.ResourceCalendar.create({
            'name': 'Test Calendar',
        })

        # Create test contract
        self.contract = self.HrContract.create({
            'name': 'Test Contract',
            'employee_id': self.employee.id,
            'state': 'open',
            'date_start': datetime.now().date(),
            'wage': 1000,
            'resource_calendar_id': self.calendar.id,
        })

    def test_generate_work_entries_cron_method(self):
        # Test the cron method
        self.HrContract.generate_work_entries_cron_method()
        
        # Check if work entries were generated
        work_entries = self.env['hr.work.entry'].search([('contract_id', '=', self.contract.id)])
        self.assertTrue(work_entries, "Work entries should have been generated")

    def test_hr_contract_update_wizard(self):
        wizard = self.HrContractUpdateWizard.create({
            'date_generated_from': datetime.now().date(), 
            'date_generated_to': (datetime.now() + relativedelta(days=30)).date(),
        })
        
        # Run the wizard action
        wizard.with_context(active_ids=[self.contract.id]).action_update_hr_contract_fields()
        
        # Check if work entries were generated
        work_entries = self.env['hr.work.entry'].search([('contract_id', '=', self.contract.id)])
        self.assertTrue(work_entries, "Work entries should have been generated by the wizard")

    def test_global_time_off(self):
        # Create a global time off
        global_time_off = self.env['resource.calendar.leaves'].create({
            'name': 'Global Time Off',
            'date_from': datetime.now(), 
            'date_to': (datetime.now() + relativedelta(days=1)),
            'calendar_id': self.calendar.id,
            'work_entry_type_id': self.HrWorkEntryType.search([('code', '=', 'WORKG')], limit=1).id,
        })
        
        # Generate work entries
        self.contract.generate_work_entries(datetime.now().date(),(datetime.now() + relativedelta(days=7)).date())
        
        # Check if the global time off is reflected in work entries
        work_entries = self.env['hr.work.entry'].search([
            ('contract_id', '=', self.contract.id),
            ('work_entry_type_id', '=', global_time_off.work_entry_type_id.id)
        ])
        self.assertTrue(work_entries, "Global time off should be reflected in work entries")

    def test_hr_work_entry_type_translation(self):
        
        self.work_entry_type_regular.with_context(lang='es_ES').write({'name': 'Regular (ES)'})
        self.assertEqual(self.work_entry_type_regular.with_context(lang='es_ES').name, 'Regular (ES)')

    def test_action_open_hr_contract_update_wizard(self):
        action = self.contract.action_open_hr_contract_update_wizard()
        if action:  # Check if action is not empty
            self.assertEqual(action.get('res_model'), 'hr.contract.update.wizard')
            self.assertEqual(action.get('type'), 'ir.actions.act_window')
            self.assertEqual(action.get('view_mode'), 'form')
            self.assertEqual(action.get('target'), 'new')